baseURL = 'https://hyperion2144.github.io/'
languageCode = 'zh-cn'
defaultContentLanguage = "zh-cn"
title = 'ä¸ä¿¡æ­¤å¿ƒå°¤æ¢—æ¢—'
theme = "kagome"
hasCJKLanguage = true

[author]
  name = "ä¸ä¿¡æ­¤å¿ƒå°¤æ¢—æ¢—"
  email = "2840956925@qq.com"
  description = "è¯·çœ‹å¤©æ—¥æ˜­å¦‚æ­"
  avatar = "https://avatars.githubusercontent.com/u/117332613?v=4"

# èœå•/å¯¼èˆªæ 
[menu]
  # é¡¶éƒ¨å¯¼èˆªæ 
  [[menu.main]]
    identifier = "/"
    name = "ğŸ ä¸»é¡µ"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "/posts"
    name = "ğŸ“–æ–‡ç« "
    url = "/posts"
    weight = 2
  [[menu.main]]
    identifier = "/topics"
    name = "ğŸ“…å½’æ¡£"
    url = "/topics"
    weight = 3
  [[menu.main]]
    identifier = "/about"
    name = "ğŸ§¸å…³äº"
    url = "/about"
    weight = 4
  [[menu.main]]
    identifier = "/link"
    name = "ğŸ”—ç›¸å…³é“¾æ¥"
    url = "/link"
    weight = 5
  
  # åº•éƒ¨ç¤¾äº¤å›¾æ ‡
  [[menu.social]]
    identifier = "github"
    name = "github"
    url = "https://github.com/hyperion2144"
    weight = 1

# URLæ ¼å¼
[permalinks]
  posts = "/:section/:year:month:day:15:04/"
  files = "/:section/:year:month:day:15:04/"
  docs = "/:section/:year:month:day:15:04/"

# ä¸»é¢˜ç›¸å…³é…ç½®é¡¹
[params]
  keywords = ['theme', 'kagome']
  description = ""
  mainSections = ["posts"]
  # å›½å†…å¤‡æ¡ˆå·
  beian = ""
  # TOCç›®å½•å‡ºç°å­—ç¬¦é•¿åº¦é™åˆ¶
  toc_show_len = 300

  [params.analytics]
    baidu = ""

  [params.widget]
    # ç›¸å…³æ–‡ç« æ¨èæ•°é‡
    articles_count = 6
    # åˆ†ç±»ç›¸å…³æ˜¾ç¤ºæ•°é‡
    categories_count = 6
    # æ ‡ç­¾ç›¸å…³æ˜¾ç¤ºæ•°é‡
    tags_count = 12

  [params.aplayer]
    theme = "#b7daff"
    autoplay = false
    loop = "none"
    mutex = true

  [params.dplayer]
    theme = "#b7daff"
    autoplay = false
    loop = false
    mutex = true

[taxonomies]
tag = "tags"
category = "categories"
topic = "topics"